name: publish

on:
  push:
    tags:
      - '*.*.*'

jobs:
  publish_and_release:
    permissions:
      contents: write # Allows this job to create releases

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org
          cache: 'pnpm'

      - name: Install deps and build
        run: pnpm install

      - name: Publish to npmjs.com
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
